### ISSUE TITLE
报错  SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by LukerSpringtree** [mongolass/mongolass#6]
哥,我最近在学习你的 mongolass 
为什么我按照 readme 上面的代码来敲 
在命令行里面 node 它  有这样的错误代码:
摸不着头绪? 能帮我看下嘛 谢谢

c:\Users\luker.springtree\Desktop\Node1\mongolass\node_modules\mongolass\lib\query.js:54
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\luker.springtree\Desktop\Node1\mongolass\node_modules\mongolass\lib\model.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by nswbmw** [comment]
用 Node@4+，然后开启 `--harmony`
